export interface QuestionData {
  question: string;
  answer: string;
}

export const quizQuestions: QuestionData[] = [
  { question: "Disebut apakah orang yg sedang berada dalam perjalanan panjang?", answer: "Musafir" },
  { question: "Perintah untuk berpuasa ada pada surah apa dan ayat berapa?", answer: "Al-Baqarah ayat 183" },
  { question: "Kitab Suci yg diturunkan kepada Nabi Daud adalah?", answer: "Kitab Zabur" },
  { question: "Nabi yg mendapat julukan bapak dari Nabi adalah?", answer: "Nabi Ibrahim" },
  { question: "Seruan atau panggilan untuk menunaikan shalat disebut dengan?", answer: "Adzan" },
  { question: "Alhamdulillahi robbil alamin disebut dengan bacaan?", answer: "Tahmid/Hamdalah" },
  { question: "Nabi yg memiliki ketabahan yg luar biasa digolongkan sebagai?", answer: "Ulul Azmi" },
  { question: "Ma'mum yg terlambat dalam shalat berjamaah disebut dengan?", answer: "Masbuq" },
  { question: "Zakat yg bertujuan untuk membersihkan diri dan dibayarkan pada saat bulan Ramadhan adalah zakat?", answer: "Zakat Fitrah" },
  { question: "Orang yg keluar dari Islam disebut dengan?", answer: "Murtad" },
  { question: "Orang yg sengaja memperlihatkan amalan baiknya agar mendapat pujian disebut dengan?", answer: "Riya" },
  { question: "Shalat yg bertujuan untuk meminta kepada Allah agar diturunkan hujan disebut dengan shalat?", answer: "Istisqa" },
  { question: "Nabi Muhammad berdakwah di Mekkah selama berapa tahun?", answer: "13 Tahun" },
  { question: "Huruf Iqlab hanya ada satu. Yaitu?", answer: "Ba" },
  { question: "Jantung Al-quran adalah surah?", answer: "Yasin" },
  { question: "Siapakah sabahat Rasulullah yg menggantikan Rasulullah untuk tidur guna mengecoh kaum kafir quraisy adalah?", answer: "Ali bin Abi Thalib" },
  { question: "Mukjizat yg diberikan kepada Nabi Shaleh adalah?", answer: "Bisa mengeluarkan unta betina dari batu besar" },
  { question: "Setelah perbekalan habis, Siti Hajar mencari air dengan berlari dari bukit?", answer: "Bukit Safa dan bukit Marwah" },
  { question: "Nama saudara Nabi Ishaq adalah?", answer: "Nabi Ismail" },
  { question: "Berapakah usia Nabi Ibrahim ketika Ishaq lahir?", answer: "100 Tahun" },
  { question: "Siapakah anak Nabi Ishaq yang akan menjadi Nabi untuk Bani Israil?", answer: "Nabi Ya'qub" },
  { question: "Surah An-nisa artinya adalah?", answer: "Perempuan/Wanita" },
  { question: "Nabi Ismail memiliki mukhizat yg sangat luar biasa, yaitu?", answer: "Mengeluarkan air zam-zam dari hentakan kakinya" },
  { question: "Manusia yg bisa menulis dan membaca pertama kali adalah?", answer: "Nabi Idris" },
  { question: "Dalam Al-Quran, surah yg tanpa Basmalah adalah?", answer: "At-Taubah" },
  { question: "Nabi yg bermimpi melihat 11 Bintang, bulan dan matahari bersujud kepadanya adalah?", answer: "Nabi Yusuf" },
  { question: "Di dalam tubuh, ada segumpal daging yg apabila baik, maka baik seluruh tubuhnya, namun apabila rusak maka rusak seluruh tubuhnya, apakah itu?", answer: "Hati" },
  { question: "Nabi yg diuji dengan meninggalnya semua anaknya dan diberi ujian penyakit kulit adalah?", answer: "Nabi Ayyub" },
  { question: "Surah dalam Al-quran yg menjelaskan bahwa manusia diciptakan dalam bentuk sebaik2nya adalah?", answer: "At-Tin" },
  { question: "Yg menemukan Nabi Musa ketika dihanyutkan di sungai Nil ketika bayi adalah?", answer: "Siti Asiyah" },
  { question: "Siapakah yg menyusui Nabi Muhammad ketika bayi?", answer: "Halimah Sa'diyah" },
  { question: "Siapa putra pertama Nabi Muhammad saw?", answer: "Qasim" },
  { question: "Siapa yg dijuluki sebagai pedang Allah oleh Nabi Muhammad?", answer: "Khalid Bin Walid" },
  { question: "Sebutkan 4 nama anak perempuan Nabi Muhammad saw?", answer: "Ruqoyyah, Fatimah, Zainab, Ummu Kultsum" },
  { question: "Shalat apa yg lebih baik daripada dunia dan seisinya?", answer: "Shalat Qabliah Subuh" },
  { question: "Apa arti dari Surah ke 104?", answer: "Pengumpat (Al-Humazah)" },
  { question: "Apa ibukota Palestina?", answer: "Yerusalem" },
  { question: "Siapa 2 Nabi yg pernah terkena sihir?", answer: "Nabi Musa dan Nabi Muhammad" },
  { question: "Siapa putri Nabi Muhammad yg paling sulung?", answer: "Zainab" },
  { question: "Siapa yg paling muda putri Nabi Muhammad?", answer: "Fatimah" },
  { question: "Siapa putri Nabi Muhammad yg menikah dengan Usman bin Affan?", answer: "Ruqoyyah dan Ummu Kultsum" },
  { question: "Orang yg beriman kepada Allah SWT disebut juga?", answer: "Mukmin" },
  { question: "Orang yg berpura2 beriman tetapi hatinya tidak meyakini?", answer: "Munafik" },
  { question: "Orang yg berjuang dijalan Allah dengan harta tenaga dan jiwa?", answer: "Mujahid" },
  { question: "Sebutkan 3 surah dalam Al-quran yg merupakan nama Nabi?", answer: "Hud, Yusuf, Nuh" },
  { question: "Sebutkan 3 surah dalam Al-quran yg artinya merupakan nama hewan?", answer: "Al Baqarah, Al Ankabut, An Naml" },
  { question: "Bacakan ayat dalam surah al Baqarah ayat 255?", answer: "Ayat Kursi" },
  { question: "Siapakah yg akan membunuh dajjal pada perang akhir zaman?", answer: "Nabi Isa" },
  { question: "Apa 2 kota yg tidak akan dimasuki oleh dajjal dan pengikutnya?", answer: "Mekkah dan Madinah" },
  { question: "Dajjal tidak akan memasuki 4 mesjid apa?", answer: "Masjidil Haram, Masjid Nabawi, Masjidil Aqsa, Masjid At-Thur" },
  { question: "Perang apa yg menjadi perang terakhir Nabi Muhammad SAW?", answer: "Perang Tabuk" },
  { question: "Ada berapa ashabul Kahfi?", answer: "7 dan seekor anjing" },
  { question: "Siapakah 2 Nabi bersaudara yg diutus untuk membebaskan Bani Israil dari firaun?", answer: "Nabi Musa dan Nabi Harun" },
  { question: "Siapa Nabi yg memiliki kemampuan menafsirkan mimpi dengan tepat?", answer: "Nabi Yusuf" },
  { question: "Nabi yg diutus kepada kaum Tsamud dan diberi mukjizat unta?", answer: "Nabi Soleh" },
  { question: "Nabi yg diutus kepada kaum Ad?", answer: "Nabi Hud" },
  { question: "Siapa nabi yg dilahirkan dari ibu bernama Sarah?", answer: "Nabi Ishaq" },
  { question: "Apa surah terpendek dalam Al-qur'an?", answer: "Al-Kautsar" },
  { question: "Berapa jumlah waktu shalat pertama yang pertama kali diterima oleh Nabi Muhammad saat peristiwa isra mi'raj?", answer: "50 kali" },
  { question: "Pada peristiwa isra mi'raj, Nabi Muhammad bertemu siapa pada langit pertama?", answer: "Nabi Adam" },
  { question: "Berapa jumlah ayat surat Al-baqarah?", answer: "286" },
  { question: "Apa nama bulan Hijriah sebelum bulan Ramadhan?", answer: "Sya'ban" },
  { question: "Apa nama shalat dengan rakaat ganjil yang dikerjakanan antara shalat isya dan terbitnya fajar?", answer: "Shalat Witir" },
  { question: "Siapakah istri pertama Nabi Muhammad SAW?", answer: "Khadijah" },
  { question: "Siapakah ibunda Nabi Isa a.s?", answer: "Maryam" },
  { question: "Tanggal berapakah Nabi Muhammad Lahir?", answer: "12 Rabiul Awal" },
  { question: "Tahun baru islam jatuh pada tanggal berapa?", answer: "1 Muharram" },
  { question: "Shalat pertama yg dikerjakan Nabi Muhammad adalah?", answer: "Shalat Dzuhur" },
  { question: "Sebutkan nama hewan yg dikendarai Nabi Muhammad dari ka'bah ke masjid Al Aqsa?", answer: "Buroq" },
  { question: "Nabi siapakah yg menasehati Nabi Muhammad agar kepada merayu Allah supaya bilangan waktu shalat dikurangi?", answer: "Nabi Musa" },
  { question: "Dalam kalender Hijriyah, bulan Ramadhan adalah bulan ke berapa?", answer: "9" },
  { question: "Nama bulan setelah Ramadhan Adalah?", answer: "Syawal" },
  { question: "Penanda waktu sahur akan berakhir disebut?", answer: "Imsak" },
  { question: "Salah satu hari yg diharamkan untuk berpuasa disebut?", answer: "Hari Tasyrik (1 Syawal)" },
  { question: "Batu hitam yg diletakkan disamping ka'bah disebut?", answer: "Hajar Aswad" },
  { question: "Apa nama perang besar pertama dalam sejarah islam?", answer: "Perang Badar" },
  { question: "Pada umur berapakah Nabi Muhammad menerima wahyu pertama?", answer: "40 Tahun" },
  { question: "Siapakah yg berada dalam kandungan ibunya selama 4 Tahun?", answer: "Imam Syafi'i" },
  { question: "Siapakah malaikat yg belum melaksanakan tugasnya sampai sekarang?", answer: "Malaikat Israfil" },
];
